name = "UAG Core"
prefix = "UAG_Core"
mainprefix = "z"

[version]
major = 0
minor = 0
patch = 0
git_hash = 8

[properties]
author = "UAG Development Team"
url = "https://github.com/uagpmc/arma3"

[hemtt.launch.default]
workshop = [
    "2369477168", # Advanced Developer Tools
    "450814997", # CBA_A3
    "1779063631", # Zeus Enhanced
    "3263684880", # UAG Units
]

[hemtt.launch.ace]
extends = "default"
workshop = [
    "463939057", # ACE3
    "2018593688", # Zeus Enhanced - ACE3 Compatibility
]