name: arma

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  sqflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check cba_settings.sqf
        uses: arma-actions/sqflint@v1.0
        with:
          args: addons/cba_settings_userconfig/cba_settings.sqf
      - name: check uag functions
        uses: arma-actions/sqflint@v1.0
        with:
          args: -d addons/uag_functions/functions/
      - name: check uag missions
        uses: arma-actions/sqflint@v1.0
        with:
          args: -d addons/uag_missions/missions/
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arma-actions/hemtt@v1
        name: Setup HEMTT
      - name: Build
        run: hemtt build
