name: arma

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  sqflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: arma-actions/sqflint@v1.0
        with:
          args: addons/cba_settings_userconfig/cba_settings.sqf
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arma-actions/hemtt@v1
        name: Setup HEMTT
      - name: Build
        run: hemtt build
