name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

jobs:
  sqflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check cba_settings.sqf
        uses: arma-actions/sqflint@v1.0
        with:
          args: addons/cba_settings_userconfig/cba_settings.sqf
      - name: check uag functions
        uses: arma-actions/sqflint@v1.0
        with:
          args: -d addons/uag_functions/functions/
      - name: check uag missions
        uses: arma-actions/sqflint@v1.0
        with:
          args: -d addons/uag_missions/missions/
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: sqflint
    steps:
      - uses: actions/checkout@v2
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
        with:
          annotate: false
      - name: Build
        run: hemtt build
      - name: Rename build folder
        run: mv .hemttout/build .hemttout/@uag-core
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uag-core-${{ github.sha }}-nobin
          path: .hemttout/@*
          include-hidden-files: true # Because .hemttout is a hidden directory
      - uses: arma-actions/workshop-upload@v1
        with:
          appId: "107410" # default
          itemId: "2936923331" # Id of item to update
          contentPath: ".hemttout/@uag-core"
          changelog: "Auto deployed by GitHub Actions"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
