name: sqflint

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test-sqflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: arma-actions/sqflint@v1.0
        with:
          args: --file addons/cba_settings_userconfig/cba_settings.sqf
